### ISSUE TITLE
how  to cross-domain？？？？？？？

### ISSUE THREAD

**Issue by 768680109** [mzabriskie/axios#1022]
I only want  to  use  jsonp ，I do not  want to  set up something for the  server like ‘Access-Control-Allow-Origin’，please。。。。how do I？？？

**Comment by AlbinoDrought** [comment]
This is more-so a browser security feature, and doesn't really have much to do with axios specifically.

To bypass prefetch requests, and skip CORS (Access-Control-Allow-Origin), [see here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests).

In short, you can perform `GET`, `HEAD`, or `POST` requests, and you can't set completely custom headers. For example, if you do a simple `axios.get('http://example.com')`, it will work cross-domain because it doesn't trigger a prefetch request.

**Comment by rubennorte** [comment]
That isn't likely a problem in Axios so can you please send this to [Gitter](https://gitter.im/mzabriskie/axios) or [StackOverflow](https://stackoverflow.com/questions/ask?tags=axios) and provide enough information to understand what problem you are having? Thanks.
