### ISSUE TITLE
Option to turn off follows-redirect

### ISSUE THREAD

**Issue by noraesae** [mzabriskie/axios#211]
Is there an option to turn off follows-redirect? It's quite critical for API tests when we would just like to check if it returns with `302`, not the redirected response.

**Comment by mzabriskie** [comment]
This is currently not an option. Would be simple enough to support though. If you want to PR I'd be happy to merge it. Otherwise I'll get to it as soon as I can.

**Comment by BigstickCarpet** [comment]
+1 to this, except that rather than a simple boolean value, I think it should be the number of requests to follow.  Setting it to zero would disable following redirects.  Setting it to `-1` would allow following infinite redirects.  Any other numeric value would be the number of redirects to follow.

This is important for preventing infinite redirect loops, and just generally for performance. For example [SuperAgent defaults to 5 redirects](https://visionmedia.github.io/superagent/#following-redirects).

A good test for this would be [https://httpbin.org/redirect/25](https://httpbin.org/redirect/25)

**Comment by nickuraltsev** [comment]
@BigstickCarpet I agree that this needs to be supported. I would be happy to accept a PR.

**Comment by nickuraltsev** [comment]
Fixed by #307
