### ISSUE TITLE
Can't bind() promise

### ISSUE THREAD

**Issue by roblav96** [mzabriskie/axios#247]
I have this method here I'm creating and I can't seem to call bind(this) on the promise chain.

```javascript
		$http_get: function ( url, sendi ) {
			this.$prog_start()
			return axios.post( this.$httpURL + url, sendi, {
				headers: this.$http_headers()
			} ).bind( this ).then( function ( response ) { // CANT BIND THIS :(
				this.$prog_success()
				console.log( 'response >', response )
				return 'datas'
			} ).catch( function ( response ) {
				this.$prog_error()
				console.log( 'response >', response )
			} )
		},
```
```
Uncaught TypeError: axios.post(...).bind is not a function
```

Every other promise based library I've used I can bind(this) like that.

**Comment by ctimmerm** [comment]
Axios does not come bundled with a promise library, so if you haven't included one yourself, whatever is available natively in your environment is used. Since `Promise.prototype.bind` is not part of the standard API that browsers and Node implement, your example won't work.

To make it work, you can include a promise library that does include `Promise.prototype.bind`, e.g. [bluebird](http://bluebirdjs.com).

Alternatively you can bind each of the functions to `this`:

```js
        $http_get: function ( url, sendi ) {
            this.$prog_start()
            return axios.post( this.$httpURL + url, sendi, {
                headers: this.$http_headers()
            } ).then( function ( response ) { // CANT BIND THIS :(
                this.$prog_success()
                console.log( 'response >', response )
                return 'datas'
            }.bind( this ).catch( function ( response ) {
                this.$prog_error()
                console.log( 'response >', response )
            } .bind( this ))
        },
```

Or if it's an option in the environment you're working in, use [arrow functions](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/Arrow_functions).

**Comment by roblav96** [comment]
I ending up doing:
```javascript
		$http_get: function ( url ) {
			this.$prog_start()

			return axios.get( this.$httpURL + url, {
				headers: this._$http_headers()
			} ).then( this._$http_done ).catch( this._$http_error )
		},
```

Basically what you said. What's weird is, I'm a bluebird junkie and I included it in my browserify bundle. I guess I'll load it on the global scope
