### ISSUE TITLE
Feature request: Custom Promise constructor

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [mzabriskie/axios#290]
Allow defining a Promise constructor instead of using globals. The current implementation requires using polyfills that use globals.

## Example
```js
axios.defaults.promise = PromisePolyfill;
axios.get('/foo');
```
or
```js
var axios_instance = axios.create({
  promise: PromisePolyfill
});

axios_instance.get('/foo');
```

**Comment by nickuraltsev** [comment]
@natlibfi-arlehiko What is the use case for this?

**Comment by natlibfi-arlehiko** [comment]
Just the general practice of avoiding globals. If, for example, the Promise is not supported and the polyfill is created only in the module's scope, like so:

```js
define(['some-promise-polyfill', 'axios'], function(Promise, axios) {

 axios.defaults.promise = Promise;
 axios.get('/foo');

});
```

**Comment by nickuraltsev** [comment]
It makes sense. I'd be happy to accept a PR.

**Comment by natlibfi-arlehiko** [comment]
Ok, I will start working on it.

**Comment by mzabriskie** [comment]
I don't understand the reasoning for wanting to keep `Promise` out of the global scope.

**Comment by natlibfi-arlehiko** [comment]
Well, in my opinion you want to control how and when polyfills are used. If you're going to supply custom implementations for native behavior you want to know which parts of your software do that.

But after taking a closer look at how to implement the features described in this issue, I don't think it's reasonable to set Promise in axios's options. Maybe the polyfill should be loaded by axios at the top of each file? Now, since [es6-promise](https://www.npmjs.com/package/es6-promise) only allows selecting which implementation to use (Native or polyfill) through modifying globals (The *polyfill*-function) I'm going to do a shameless self-reference to this [project](https://www.npmjs.com/package/es6-polyfills) which allows you to select the implementation automatically **without** polluting the global namespace.

**Comment by le0nik** [comment]
+1. It would be great if it used global Promise by default, but user could redefine the promise implementation. For example, in React-based isomorphic app one might want to use Bluebird for the server-side and es6-polyfill(which is much lighter if you don't need Bluebird features, like map, filter etc on the frontend). Then he could just add it as `axios.defaults.Promise = Bluebird` or `axios.Promise = Bluebird`.

It's a widely recognized pattern. See, for example
* [mongoose](http://mongoosejs.com/docs/promises.html) library. Section `Plugging in your own Promises Library`
* [node-fetch](https://github.com/bitinn/node-fetch#usage)

While you might argue, that one can attach it to the `global` or `window` object, many developers prefer not to do that and be explicit.

**Comment by Morgul** [comment]
+1 Here's my use case: I use Bluebird on the server side. I also want to use axios on the server side for accessing some external REST APIs. However, since I'm on node 5, axios returns promises that work with the default Promise implementation, and I have to wrap them whenever I want to use `.map` or the like, which is common.

My choices are to either patch the global Promise, or tell axios which promise library to use. I'd rather do the latter.

**Comment by rubennorte** [comment]
We need to start thinking about `Promise` as we think about `Object`. It is now a core feature of the language and we shouldn't expect libraries to use a different implementation (as we don't do that for Object, Array, Function or RegExp).

If you want to use a different Promise implementation in the backend and in the frontend you can do that either way (I suppose you can have specific polyfill files for each environment).

If you want to use `.map` or another custom method from Bluebird you can use the static version (`Bluebird.map(promises, fn)`) or you can wrap the promises returned by Axios (`Bluebird.resolve(axiosPromise).map(fn)`).

**Comment by jvmccarthy** [comment]
Hi @rubennorte, funny that I was working on a PR at the same time you were closing this issue. I'm glad to see that promises are now a native feature, but I still think there are reasons for making promises pluggable.

Thank you and the team for your work on axios and for your consideration.

**Comment by leonid-bauxy** [comment]
@rubennorte `axios` supports IE8+. You can't say, that Promises are a native feature, unless `axios` drops support of all browsers, that don't implement them natively.

For example, I recently had a use case, where I couldn't redefine globals, because I didn't own the environment(was developing a widget), but I also had to support browsers, that don't support Promises natively. So the code would just crush on `axios`. The only thing I can do is control which promise library is used by all the code in the widget. And I can't do that with `axios`. So I had to use another xhr library.

**Comment by le0nik** [comment]
@rubennorte `axios` supports IE8+. You can't say, that Promises are a native feature, unless `axios` drops support of all browsers, that don't implement them natively.

For example, I recently had a use case, where I couldn't redefine globals, because I didn't own the environment(was developing a widget), but I also had to support browsers, that don't support Promises natively. So the code would just crush on `axios`. The only thing I can do is control which promise library is used by all the code in the widget. And I can't do that with `axios`. So I had to use another xhr library.
