### ISSUE TITLE
[Question] what advantage does axios give us over fetch? EOM

### ISSUE THREAD

**Issue by es6Test** [mzabriskie/axios#314]

**Comment by mzabriskie** [comment]
Overall they are very similar. Some benefits of axios:

- Transformers: allow performing transforms on data before request is made or after response is received
- Interceptors: allow you to alter the request or response entirely (headers as well). also perform async operations before request is made or before Promise settles
- Built-in XSRF protection

**Comment by niftylettuce** [comment]
I wrote a fetch implementation, which was inspired by axios, superagent, and request here https://github.com/glazedio/frisbee.  I really do wish `axios` used `fetch` though!!! I love this package.

**Comment by mzabriskie** [comment]
@niftylettuce I started this project before `fetch` was a thing. Haven't really seen any justification in refactoring. What benefit would using `fetch` provide?

**Comment by rockallite** [comment]
* _fetch_ has yet to provide a standard way of aborting a request. ([#27](https://github.com/whatwg/fetch/issues/27))
* Therefore, _fetch_ has failed to provide an API to set `timeout` option. ([#20](https://github.com/whatwg/fetch/issues/20))
  * ...which means that you'll have to wait 30 seconds (by default) before a network timeout error happens.
  * ...or, use `setTimeout` or `Promise.race` to manually reject the returned promise, if you need a shorter timeout. And it has a tiny side effect ([#175](https://github.com/github/fetch/issues/175)):

    > _**mislav** commented on 29 Jul 2015_
    > ...with the above implementation, even if the timeout happens, the original request won't be aborted because we don't have an API to abort fetch requests. Instead, **the request will complete in the background but its response will get discarded**.

* See the comments of [this blog post](https://hacks.mozilla.org/2015/03/this-api-is-so-fetching/). And I'm totally agree with the following one:
  > _**J W**_
  > Although the standard loosely talks about timeout’s, they never explain as to how you would specify one either. Unfortunately, **a complete deal breaker** for any use cases that I would use it for.
  > _March 17th, 2015 at 15:02_

* For any serious browser-based projects, pick a solid AJAX library like _axios_, or even _jQuery_, not the experimental _fetch_.

* Notice that all the above opinions are based on [_fetch_](https://github.com/whatwg/fetch) (or its [browser polyfill](https://github.com/github/fetch)), not [_node-fetch_](https://github.com/bitinn/node-fetch).

**Comment by es6Test** [comment]
I see, I'm surprised the fetch guys haven't sorted this yet.

**Comment by GanbilegBor-minted** [comment]
Also as of right now `fetch` is not supported on any [Safari and EI versions](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) (scroll down), unless you want to add a polyfill. And unfortunately even if you're using babel `fetch` polyfill doesn't come with it so it's a little bit of extra work to add a polyfill like [this one](https://github.com/github/fetch).

**Comment by larsnystrom** [comment]
Fetch does not support [upload progress](https://github.com/whatwg/fetch/issues/21).

Perhaps the information in this thread could be added to the readme? I think there are plenty of people who choose fetch over xhr just because it's the shiny new thing, and then have to refactor a bunch of code as they realise fetch doesn't support as many use cases as xhr does.

**Comment by pke** [comment]
@larsnystrom I also just now discovered axios because of `apisauce` using it. I wondered why it didn't use `fetch`. I am using `fetch` because its the default for any `reactjs` sample out there.
But after reading this comparison here I'll ditch `fetch` because I want timeouts and always wondered why `fetch` does not have it. And if you see the referenced issues over there, they are so old I doubt they will ever end up in `fetch`.

So I think a comparison of two libraries on the front pages' readme helps people to choose one over the other.

**Comment by dmt0** [comment]
@mzabriskie One reason you might want to use fetch is if you want to make an offline-first app using Service Worker API: https://developers.google.com/web/fundamentals/getting-started/primers/service-workers

With fetch you can add event listeners for Service Worker to intercept. Haven't found a way to do that with XHR yet.

**Comment by Haocen** [comment]
According to http://caniuse.com/#search=fetch , the native support for fetch is fantastic now.

**Comment by niftylettuce** [comment]
Just FYI - my axios inspired implementation (that uses `fetch`) has a new link / repository at <https://github.com/joinspontaneous/frisbee>!  The only downside I think is that fetch API won't let you stop/cancel a request in process.

**Comment by vzaidman** [comment]
@niftylettuce and no "upload progress" right?

**Comment by niftylettuce** [comment]
correct @vzaidman (see https://github.com/github/fetch/issues/89), but for handling file uploads  progress you could always use websockets

**Comment by larsnystrom** [comment]
@niftylettuce No, not always. You need permissions to run a WebSocket-server on your host. That’s not always a possibility. Many people have sites on cheap hosts with LAMP-stacks. Even when you have full control of your web host, the fact that you have to change your server-side code to deal with file uploads just because you decided to use fetch over XHR in the client should give paus for thought.

**Comment by niftylettuce** [comment]
it was a suggestion dude

**Comment by gustawdaniel** [comment]
There is great article about this:

> https://medium.com/@thejasonfile/fetch-vs-axios-js-for-making-http-requests-2b261cdd3af5

**Comment by vzaidman** [comment]
not so great since it discusses only one minor difference as far as i see

**Comment by ruchern** [comment]
Axios interceptors for me. That is a breeze to setup configuration for a global content.
