### ISSUE TITLE
It seems axios does not support jsonp call

### ISSUE THREAD

**Issue by shaosh** [mzabriskie/axios#342]
I am trying to use axios to send jsonp call by setting dataType="jsonp" in the config field, but it returns error like "No 'Access-Control-Allow-Origin' header is present on the requested resource." I finally figured out the reason is axios does not support jsonp calls. I am wondering if there is any plan to add the jsonp support. 

Thanks.
shaosh

**Comment by nickuraltsev** [comment]
There are no plans to add support for JSONP. I would suggest you to consider using CORS for cross-domain requests instead.

**Comment by Frondor** [comment]
And this is how you screw a good library.

**Comment by ProteanCode** [comment]
> And this is how you screw a good library.

Yes and no. 

Jsonp is a wide-spreaded hack for what CORS is. You can't go wrong with not implementing hack solutions, but on the other hand you either won't avoid people's rage since 99.99% of developers expect any request lib to support that feature.

There are a lot of things that could be done better in the past. but we suffer from it today (like FTP protocol). I am waiting for Filezilla to stop using FTP and force people to buy servers with hucking SSH/SFTP access to it ffs.
