### ISSUE TITLE
Add request data in response interceptor's error callback

### ISSUE THREAD

**Issue by ingro** [mzabriskie/axios#425]
Hello! I've created a response interceptor with the main purpose of catch globally the errors and notify them to [bugsnag](https://bugsnag.com/).

The problem I'm facing is that I've not access to the request which generated the response error, so I lack precious data to analyze the errors on bugsnag.

Is there another way to achieve this or do you think that adding that data could be useful and included in a future release?

Thank you.

**Comment by damianprzygodzki** [comment]
+1 I can't get error status at all

**Comment by nickuraltsev** [comment]
The `error.config` property should contain the [request config](https://github.com/mzabriskie/axios#request-config). 

Hope this helps!

**Comment by damianprzygodzki** [comment]
Yeah, there it is (if anyone still got the problem check your version).

But i am wondering, that something is missing (or documentation, or implementation) or it is unclear.

For example, when i follow documentation, and want to log error:

`axios.interceptors.response.use(function (response) {
    return response;
}, function (error) {
    console.log(error);
    return Promise.reject(error);
});`

It returns only Error message "Error: Request failed with status code 405". So the last thing it would be trying to call error properties `error.response`. 

So it should be more elaborated in docs, or for me more clear and straightforward solution is to just provide this heck error object, because i belive, any web dev would be handling his error with this message "Error: Request failed with status code 405".

**Comment by ingro** [comment]
Thanks @nickuraltsev for the insights, I also agree with @damianprzygodzki that this feature should be better documented, great work with axios anyway!
