### ISSUE TITLE
Interceptor should continue to the respective next / catch method

### ISSUE THREAD

**Issue by GGAlanSmithee** [mzabriskie/axios#449]
As mentioned by @mbektimirov in https://github.com/mzabriskie/axios/issues/41#issuecomment-124162471 an interceptor that intercepts a `catch` will continue to the `next` method of the `Promise` (unless re-thrown as an `error`). I think this is non-intuitive and breaks the logical flow of execution. The way I see it, an interceptor should intercept and continue, not change the execution flow.

In other words, I would expected this

``` javascript
axios.interceptor.response.use(
    response => response,
    error => error
)
```

to continue to the `next`/`catch` method of the `Promise` respectively, but as implemented, both interceptors will continue to the `next` method.

Is there any particular reason why it is implemented this way that I am not seeing?

**Comment by GGAlanSmithee** [comment]
Thinking some more about it, it is probably like this because it allows you to chose where to go;

* `return error` goes to `fetch`
* `Promise.reject(error)` goes to `catch`

I guess it would be hard to implement the same if `return`ing would go to `catch`.

**Comment by fakiolinho** [comment]
I 've started using Interceptor recently to handle failed ones globally but it seems I cannot avoid getting into `catch()` after `Promise.reject(error)` is used. So let's say a 401 is returned by the server and I have to logout the user by force and redirect him to login page. This is a very common error that could be handled globally in a SPA. Unfortunately, i still have to pass through `catch()`. If I omit `catch()` in cases like this one, then an `unhandled exception` is thrown. Is this the wanted behavior? How you tackle these occasions?


I don't want to return an error and get into `then()` because things will become messy there.

**Comment by rubennorte** [comment]
@GGAlanSmithee it's implemented that way so you can recover from errors returning a new promise.

@fakiolinho, you need to intercept errored responses in that case to redirect the user. Something like:

```javascript
axios.interceptors.response.use(null, (error) => {
  if (error.response && error.response.status === 401) {
    window.location = '<login-url>';
  }

  throw error;
});
```

**Comment by NanoDev777** [comment]
@rubennorte  
can you check this thread please take time without solving this problem https://github.com/axios/axios/issues/1290
