### ISSUE TITLE
Share config object between request and response interceptors

### ISSUE THREAD

**Issue by DjebbZ** [mzabriskie/axios#520]
Hi,

My understanding of the docs is that if I modify the `config` object passed to the request interceptor, I can retrieve this modified version in the correspondig response interceptor, under `response.config` or `error.config`. My use case : log all requests/responses and attach a UUID to both the request and response log messages to be able to track down problems more easily.

Basically I'm doing something like this :

``` javascript
axios.interceptors.request.use((config) => {
    config.__requestId = generateUUID();
    log(`Request ${config.__requestId} : ...`); // simplified for brevity
    return config;
});

axios.interceptors.response.use((response) => {
    log(`Response from ${response.config.requestId} : ...`);
    return response;
});
```

I was expecting this to work since `config` is `return`ed from the request interceptor, but it doesn't. Is this by design ? A bug ? Is my issue a feature request ? Could you help ?

Thanks in advance !

**Comment by DjebbZ** [comment]
By the way, I know there are already issues about the config object, I did read them all.

**Comment by rubennorte** [comment]
I reviewed the code and it should work as you describe. I noticed that in your example you use `config.__requestId` in the request interceptor and `config.requestId` in the response interceptor. Is it a bug in your code or a typo in the example?

**Comment by DjebbZ** [comment]
Typo in my example. I tried just before posting to be sure and `response.config.__requestId` was `undefined`.

**Comment by loklaan** [comment]
I just noticed this behaviour!

The original config is not passed to the response's `config` property. Instead a [mutated][mutate] object is [passed][pass] to the configured adapter.

A fix for this could potentially be too shallow copy the config, and pass that as a second argument to the adapter so that they can use it on `response.config` instead of the mutated config.

But I suppose this mutative behaviour on `response.config` is the expected in some codebases by now... For now, I am depending on it so that a response interceptor can (re)parse the `config.data` back to an object 🙃.

If the project wants to fix this, it must either:
1. Make a breaking change, replacing the value of `config` property to the original
2. Add to the response by attach another property, such as `originalConfig`, with the value of the original request config

If a major release is already around the corner, then  no. 1 is better.

[mutate]: https://github.com/mzabriskie/axios/blob/cfe33d4fd391288158a3d14b9366b17c779b19e3/lib/core/dispatchRequest.js#L30
[pass]: https://github.com/mzabriskie/axios/blob/cfe33d4fd391288158a3d14b9366b17c779b19e3/lib/core/dispatchRequest.js#L52

**Comment by loklaan** [comment]
Oh I didn't notice that axios was major version zero, woot 'easy' breakages. _(I did notice the upgrade doc, which would need to be updated for this change)_

I am happy to put a PR together. Would appreciate some feedback from collaborators before jumping into it prematurely though, thanks!

**Comment by rubennorte** [comment]
I just did this quick test and worked fine:

```javascript
var axios = require('axios');

axios.interceptors.request.use((config) => {
  config.foo = 'bar';
  return config;
});

axios.interceptors.response.use((response) => {
  console.log('Foo config', response.config.foo);
  return response;
});

axios.get('https://github.com');
// 'Foo config bar'
```

If you have a failing test please reopen the PR with more context information.

**Comment by SimonOdell** [comment]
How would you access config.foo if the request fails (ie, your app is offline) I need to find a way to serve requests from indexedDB when there is no connectivity

**Comment by SimonOdell** [comment]
I've solved the problem now; I wrote my own promised based object wrapper around axios which takes the same arguments so no need to patch the rest of the code, and it manages the request and responses with it's own internal state which can be referred to if the axios request fails.
