### ISSUE TITLE
What is the purpose of PROTECTION_PREFIX in default transformResponse?

### ISSUE THREAD

**Issue by dominykas** [mzabriskie/axios#555]
This is question is about [this regex `replace()`](https://github.com/mzabriskie/axios/blob/5faebabcd8f065e312b5c92081433d6ae1ef8c8f/lib/defaults.js#L59).

I've looked in the issues, I've looked in the history and I've looked in the unit tests - but I couldn't find any clues - there doesn't seem to be an assert for it or any comments?

I'm happy to PR a config setting or a removal of this option - ~~but for the use case I'm working with, it is not necessary, yet highly costly - Chrome seems to allocate memory for the copy of the whole response to do the regex replace/match. Considering, that the response I'm working with can go as high as 250Mb - doubling the RAM usage for just that one request becomes quite painful and occasionally leads to out of memory errors.~~ I misinterpreted the profile results - despite the fact that the regex replace allocates a lot of memory, there's even more memory that needs to be allocated for the JSON.parse anyways.

As a workaround, we'll try to use a custom, simpler transform, yet I'm still wondering whether this should be the default behavior?

Thanks.

**Comment by nickuraltsev** [comment]
It's JSON vulnerability protection. You can read about it [here](http://stackoverflow.com/questions/28806624/how-does-the-angularjs-json-vulnerability-protection-work). The vulnerability itself is discussed [here](http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx/). 

Since the problem exists only in Firefox 2.0 or earlier, I think we can get rid of this code.
