### ISSUE TITLE
Can't identify a relative url if baseURL is set

### ISSUE THREAD

**Issue by shlomitc** [mzabriskie/axios#618]
I want to log relative url calls using an interceptor, but also want to add a baseURL to my requests.
The following code will not work because baseURL is already combined with the called url when interceptor is applied.

```
import axios from 'axios'

axios.defaults.baseURL = 'http://www.mysite.com';

axios.interceptors.request.use(config => {
  if (!config.url.match(/^http/)) {
    console.log('you made a relative url call');
  }
  return config;
});

axios.get('/api');
```

There should either be an explicit way to identify the original called url, or delay combining the baseURL until interceptor finishes.

**Comment by rubennorte** [comment]
We apply all the defaults and compute URLs before all interceptors all called. It's that way by design. If we delay combining the baseURL then we would break all interceptors that already use that feature.

If you need to know if the URL belongs to the site you can check the current URL in window.location. If you really need the exact URL used to call Axios the only solution I can think of is overwriting `axios.request`.

**Comment by altinselimi** [comment]
Hello, so how would I go about accessing a relative path after I've set my baseURI?

For example: baseURI is 'http://myapi.com', and I want to call '/config.json' from the path I am right now (localhost:8080/config.json)?
