### ISSUE TITLE
Use in webworker

### ISSUE THREAD

**Issue by SamyPesse** [mzabriskie/axios#70]
Since `document` is not accessible in webworkers, Axios can't be used.

Is it possible to handle webworkers ?

**Comment by mzabriskie** [comment]
I would have to look to see where `document` is being used. But I think this could be accomplished.

**Comment by mzabriskie** [comment]
Looks like `document` is being used in two places:

- lib/helpers/cookies.js
- lib/helpers/urlIsSameOrigin.js

Would need to find a way to make things work in the case where `document` doesn't exist.

**Comment by Blechhirn** [comment]
@mzabriskie Would it be possible to make the cookie-based XSFR header an opt-in rather than the default? Reading cookies from a worker won't work anytime soon, so all you can do really is pass in the information from the main script and inject it into the call to axios - which renders this convenience functionality kind of useless as you could as well inject the header directly.

I would be willing to take a crack on this task, but it would be a behavior change I'd rather bring up first.

**Comment by skevy** [comment]
@mzabriskie With urlSameOrigin...is all that's happening there just the url parsing (and you didn't want to depend on an external lib)?

**Comment by skevy** [comment]
Yah, I'd agree with @Blechhirn that the xsrf should be opt-in. It's nice to have...but a lot of API's don't need it.

**Comment by skevy** [comment]
I'll send a PR if you're down to make that change.
