### ISSUE TITLE
How to check axiosInstance instanceof axios?

### ISSUE THREAD

**Issue by xarnze** [mzabriskie/axios#737]
Hi,

Does anyone know if it's possible to check if an object is an instance of axios? e.g.

```
var axios = require(axios);

var axiosInstance = axios.create();

if(axiosInstance instanceof axios){
// do something
}

```

**Comment by rubennorte** [comment]
Not sure why it was done the way it is, but `axios` is not a class/constructor and `axios.create` doesn't return an instance of it.

I recommend you to check the existence of a specific interface (like the `request` function) instead of using `instanceof` that could have a weird behaviour in some contexts.
