### ISSUE TITLE
HTTP post error: Error: Network Error

### ISSUE THREAD

**Issue by TracyDa** [mzabriskie/axios#751]
I'm working with react-redux and axios,I can send http get request now,but when I post http request,I got this errror:
```

HTTP post error:  Error: Network Error

createError@webpack:///./~/axios/lib/core/createError.js?:15:15
handleError@webpack:///./~/axios/lib/adapters/xhr.js?:87:14

```

my server include these headers in response,I used to use ajax to post http request,and they work well,but now,I just can't post http request,am I missing something?What else do I need to do?

```
headers['Access-Control-Allow-Origin'] = '*'
headers['Access-Control-Allow-Methods'] = 'PUT,GET,POST,DELETE,OPTIONS'
allow_headers = "Referer,Accept,Origin,User-Agent,Content-Type"
headers['Access-Control-Allow-Headers'] = allow_headers
```

My js code:

```
export const post_http = (url, param) => {
    return (
        axios.post(`${url}`, param, header)
    )
};
```

Response
```

Allow: POST, OPTIONS
Connection: keep-alive
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Thu, 09 Mar 2017 01:26:24 GMT
Server: nginx/1.11.8
```

And status code is 200.

**Comment by leizard** [comment]
Did you check this solution ?
http://stackoverflow.com/questions/38418998/react-native-fetch-network-request-failed

**Comment by TracyDa** [comment]
@leizard Thanks for your help,but they're very different.

**Comment by TracyDa** [comment]
Solve this by myself,actually for me I don't need to add `Access-Control-Expose-Headers`.

Need this:

**Comment by arryanggaputra** [comment]
same here

**Comment by wkarim86** [comment]
I have had the same issue and hit my head on the desk for 1 hours to fix this. Finally, I got the resolution.
Follow the Step : 
1. Remove "build" directory inside "ios" 
2. Run the following commands 
     react-native upgrade            //enter Y if you haven't modified asking files
     react-native link 
3. Go to "ios" directory then [your-project-name] directory open Info.plist 
4. Add the below code under "**NSAppTransportSecurity**" 
<key>NSAppTransportSecurity</key>
<dict>
  
  <key>NSAllowsArbitraryLoads</key>
      <true/>
</dict>
5. react-native run-ios

Hope it will work for your as it worked for me.

**Comment by ikosar** [comment]
Make Sure **"http://"** is in your URL Address .

**Comment by omair115** [comment]
make sure when you are downloading axios library turn off your emulator or connected device and make API call with https.

**Comment by falialahati** [comment]
@da2018 i have such problem but by your approach i cant solve that.

**Comment by scmyhexinhao** [comment]
Guys, I also struggling on this issue for quit while. But I figured out the issue of my axios post network createError on Android device now. The reason to axios Network Error is because the form data I passed to axios contains wrong type of data object I guess. I have include an image object(ImagePicker object from Expo) as a one of param of form data which not accept by axios I think. Axios might only receive string, float, int or image as param. image cannot pass as param, it is not an type of image, it is an react native object, I have removed it and include an image field as param by assign image.uri to value of param then it works. Hope this will help some of people who may encounter same problem as I was facing before. 
  Deleting some of your form data one by one when you are testing axios Network error, you will find out which one is the cause of issue.

**Comment by waleedarshad** [comment]
Adding this resolved my issue in api suace

`  "Content-Type": "application/x-www-form-urlencoded",`
    `  Accept: "application/json" `

**Comment by loverdeveloper** [comment]
> @da2018 i have such problem but by your approach i cant solve that.

Are you sure that your URL include `http://` or `https://` ?

**Comment by KBiswas98** [comment]
1. change from **localhost** to your **ip**
2. add **http://** 

http://192.168.43.49:3000/user/
