### ISSUE TITLE
Spread for catch?

### ISSUE THREAD

**Issue by samzhao** [mzabriskie/axios#76]
Hi,

First of all, thanks for the awesome library with such an intuitive API :)

I'm trying to send multiple requests at the same time with the `axios.all` helper. It works quite seamless, but when I try to catch server errors like this

```js
axios.all(requestPool).catch(function(err) {})
```

The `err` only contains the errors of the last request in the request pool.

I learned that you can use `axios.spread` in the `then` callback, so I was wondering if there is a way for `spread` to work in the `catch` callback as well?

Thanks!

**Comment by mzabriskie** [comment]
This is a good idea, and should be supported. Thanks for "catching" this :)

**Comment by theverything** [comment]
I'm not sure this is a bug because of the [Fast Fail](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#Promise.all_fail-fast_behaviour) behavior of Promise.all.

axios.all just passes the array of promises to Promise.all and then returns the resulting promise.

Seems like the only way to make this work would be to implement your own axios.all function that catches all errors and then returns them. This might be unintuitive because it goes against the spec of Promise.all.

**Comment by mzabriskie** [comment]
After consideration I don't think that this will work. If you have a pool of requests any request failing will result in a rejected Promise. The first failing request will be the culprit.

```js
Promise.all([
  Promise.reject(Error('foo')),
  Promise.reject(Error('bar')),
  Promise.reject(Error('baz'))
]).then((results) => {
  console.log(results)
}, (error) => {
  // Logs "foo" everytime
  console.log(error.message)
})
```

So ultimately you will not get an array of errors, just the first failing request.

**Comment by adk96r** [comment]
Is there any other way to let `axios.all` finish all the requests and have a spread of responses in the catch block ?
