### ISSUE TITLE
Cannot resolve module 'jsx-loader' error after version 0.4.2

### ISSUE THREAD

**Issue by tylermcginnis** [mzabriskie/axios#77]
Axios version 0.4.2 and under work fine but when I upgrade to 5.0 or anything higher than that I'm getting this error whenever I try to require axios.
```
ERROR in (webpack)/~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve module 'jsx-loader' in /usr/local/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/timers-browserify
 @ (webpack)/~/node-libs-browser/~/timers-browserify/main.js 1:15-44
```

I have a very simple webpack config file
```
module.exports = {
  entry: "./app/App.js",
  output: {
    filename: "public/bundle.js"
  },
  module: {
    loaders: [
      {test: /\.js$/, loader: 'jsx-loader'}
    ]
  }
};
```

I'm confident the error gets thrown when I try to `require('axios')`. I'm not confident this is an axios issue.

**Comment by mzabriskie** [comment]
Between 0.4.2 and 0.5.0 I made some changes to axios' webpack config, but I don't see how that would affect your build. I am using axios with webpack on this [repo](https://github.com/mzabriskie/react-example), and not seeing any problems. Have you tried using `babel-loader` instead of `jsx-loader`?

**Comment by tylermcginnis** [comment]
`babel-loader` works. Not sure what's up with `jsx-loader`. Thanks for the suggestion (and for Axios!).
