### ISSUE TITLE
Handling error in interceptor without propagating to caller

### ISSUE THREAD

**Issue by niklabaz** [mzabriskie/axios#855]
Imagine a response error that needs to be handled completely in an interceptor without propagating it to the `.catch` on the `axios.[method]` caller.

```
axios.interceptors.response.use(response => response, (error) => {
    if (error.response) {
      if (error.response.status === 401) {
        dispatch('logOut');
        notify('Session expired');
      } else return Promise.reject(error.response);
    } else if (error.request) notify('Server down');
    else notify('Unexpected error');
  });
```

So the only wanted error to be propagated is when a response exists but it's status is not 401. In that case the caller of the `axios.[method]` function can catch the `error.response` directly as `.catch(response)`.

If this cannot be achieved then the `axios` caller must do it's thing after it checks that `error` has a response and it's status is not 401. It would be checking again because the interceptor already checked and solved those cases so the caller will just ignore them. Maintenance would be a nightmare if a new check is added to the interceptor, each `axios` call will need to ignore that check because it was already handled.

Am I missing something on how Javascript works (sorry if this is the case) or it can be solved using the axios API?

**Comment by ksherman** [comment]
+1 I'm thinking about this too

**Comment by rubennorte** [comment]
You can do it with Axios. When the error response interceptor returns a value or a promise, it'll use that value to resolve the returned value from Axios. If you want to re-throw the error you must throw or return `Promise.reject(...)`.

**Comment by aocneanu** [comment]
+1 This would be really useful

 @rubennorte I think that what @niklabaz wants is to use the interceptors to catch certain errors, and let the others to go to the `.catch` method from the `axios[method]` call.

The problem is that if you throw or return `Promise.reject(...)` after you, let's say notify the user in the interceptor, then you must catch the error again, in the `.catch` method, or it will break you code.

If you instead return a `console.log()` or a toaster for the specific errors that you cover in the interceptor, axios will consider that the response is a success and then execute the code in in the `.then(response => {}` method.

How can this be addressed?

**Comment by rubennorte** [comment]
@aocneanu I think that what you're suggesting is breaking the promise chain at that point, and I'm afraid promises don't support that.

You could do it returning a never resolving promise (e.g.: `return new Promise(() => {});`) but I'm not sure if that would cause memory leaks.

Anyway that's out of the scope of Axios and must be managed in the interceptor.

**Comment by aocneanu** [comment]
Thank you for your response.

So it seems that the only way to handle certain errors globally would be to write a handler mixin and  use it in every `axios[method].catch(err => handler(error))`.
