### ISSUE TITLE
v0.16.2  after import throw an error

### ISSUE THREAD

**Issue by Shafley** [mzabriskie/axios#936]
when webpack config  target= 'node'
and import axios, after build, I required dist/index.min.js,  throw an error:
    false = namespaces;
    ^^^^^
ReferenceError: Invalid left-hand side in assignment
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:545:28)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (src/example/index.js:2:19)
    at Module._compile (module.js:573:32) 

if I don't import axios, or webpack.config target='web', no error
webpack@2.5.0
node@7.0.0

**Comment by rubennorte** [comment]
That issue doesn't seem related to axios (as we have no `namespaces` variable). Please review the rest of your code.

**Comment by srmelody** [comment]
Hi @Shafley This issue is likely caused by the DefinePlugin in webpack mangling an underlying transitive dependency of axios, the visionmedia/debug used by follow-redirects.  There is some information here that might help you work past this issue:

https://github.com/webpack/webpack/issues/4000

If you build your webpack, you probably have code like this (this is for the node environment in https://github.com/visionmedia/debug/blob/master/src/node.js) :
````
function save(namespaces) {
  if (null == namespaces) {
    // If you set a process.env field to null or undefined, it gets cast to the
    // string 'null' or 'undefined'. Just delete instead.
    delete false;
  } else {
    false = namespaces;
  }
}
```` 
You might also be able to solve this by using webpack's target to make sure you are targeting for the web.  Though from your comment, I think you are using the node (or some other non-web) target on purpose.  Good luck!
