### ISSUE TITLE
axios in edge don't woking have error

### ISSUE THREAD

**Issue by yamateH-ch** [mzabriskie/axios#956]
vue2.0+axios
I used Axios in edge browser to make a mistake :
XMLHttpRequest: network error 0x2efd, this operation cannot be completed because of an error 00002efd. 
,but in chrome  , I can request data ,
 my code: 
   getMenu: function() {
				var vm = this;
				axios.get(vm.baseUrl+'/roleInfo/role-info!getMenu.action') 
				 .then(function (response)  {   
					vm.modules = response.data;  
				}).catch(function (error)  {  
					   console.log(error);  
				});
			},
What causes it and how to solve it?

**Comment by ClickSimply** [comment]
There seems to be an open issue with Edge regarding this issue, might not be related to Axios at all.

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7183548/

Try using a different AJAX library and see if the same problem happens with that specific request in Edge.

**Comment by yamateH-ch** [comment]
@ClickSimply 
 thanks，I tried using Ajax, but the error was the same. Was it cross domain?

**Comment by ClickSimply** [comment]
Cross domain is when  you're making an ajax request to a url that isn't the one running the ajax script.

For example, if you had your app running on domainA, any ajax requests made to a domain other than domainA will be considered cross domain.

Cross domain requests typically follow very strict guidelines on what they can and can't do, they're limited quite a bit when compared to a same domain request.

Anyway, if you tried another library and the same problem happened than it's safe to say that Axios isn't responsible for the issue. 

The problem is going to be related to your use case and Edge.
